### ISSUE TITLE
Provide a start VM button after successful disk image build

### ISSUE THREAD

**Issue by odockal** [podman-desktop/extension-bootc#574]
### Is your feature request related to a problem? Please describe

It would be very nice to provide user with a start VM button that would enable the user to spin up the VM from fresh disk image that was just built via the extension.

### Describe the solution you'd like

Depending on the os/platform and the vm provider available, we could introduce new button that would lead to a form that would offer to start a VM based on previous step, which was image disk building (image type, etc).

I would have to detect possible vm provider or let user to pick it up or install it.

**Comment by cfergeau** [comment]
https://github.com/containers/podman-bootc can be used for this.

**Comment by cdrage** [comment]
We now have two places for this button now that https://github.com/podman-desktop/extension-bootc/pull/865 is in.

The buttons are there, and the next part is support for Windows and Linux VM running: https://github.com/podman-desktop/extension-bootc/issues/879 and https://github.com/podman-desktop/extension-bootc/issues/878

![Image](https://github.com/user-attachments/assets/1713eaf8-ef24-49a8-9ec7-f5e52d39603d)

![Image](https://github.com/user-attachments/assets/3fa12a2d-2669-4d07-9a8e-c976d8ba820d)

Marking this as closed as we will be tracking this development in other issues.
