### ISSUE TITLE
RFE: Add "Unattended Baremetal Installer" option

### ISSUE THREAD

**Issue by mrguitar** [podman-desktop/extension-bootc#827]
### Is your enhancement related to a problem? Please describe

Right now the ISO option creates an automated install (that's good!). ....except when you want to make an ISO for someone else and want them to answer the anaconda spokes (users, passwords, disk layout, etc).

### Describe the solution you'd like

BIB now lets us customize the installer experience, so I think it would be awesome to either have a separate "Interactive aremetal Installer" option, or better yet just have a "Baremetal Installer" option and have a radial button that can select between unattended & interactive.  

### Describe alternatives you've considered

I originally thought we needed a third option for advanced or custom kickstarts, but this is already covered by the Build Config window accepting TOML/JSON. Currently it's possible to create an interactive installer using this field, but I think it makes since to have a big easy button for this. Lastly, I think the default anaconda modules that are enabled are sufficient for what's needed. Others may disagree; I'm not sure.

### Additional context

Under the covers this is the behavior we get when the kickstart file only includes the ostree container command. ...and Simon just wrote a nice blog post on the topic: https://supakeen.com/weblog/building-interactive-installer-bootc.html

**Comment by vrothberg** [comment]
That sounds like a super useful addition, @mrguitar.

The installer options can be set as described in the [BIB docs](https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#anaconda-iso-installer-options-installer-mapping).  @mrguitar, could you share how the exact kickstart options should look like?  The same as in the [docs](https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#anaconda-iso-installer-options-installer-mapping)?

Cc: @deboer-tim @cdrage @jeffmaury

**Comment by cdrage** [comment]
@vrothberg @mrguitar Bit confused, since this is talking about kickstart.

Kickstart's are usually very convoluted / customized / a lot of information and having the entirety of that I would feel would be very complicated.

That and the fact that it's only applicable to iso's being built. 

I would make the opposite approach and ask that we maybe implement the build config options as interactive? https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#-build-config

That means it applies to all image formats (qcow, raw, iso, etc.) in terms of customizations and gets us in a better position of "inject your ssh public key" into the image and then it's all happy.

Please correct me if I'm wrong though, sorry!

**Comment by cdrage** [comment]
Hi @vrothberg @mrguitar 

After discussions with @deboer-tim in a previous call, we are going to go ahead with the implementation of a way to "automatically generate build config" with pre-defined details (ssh key, user, password, etc) for build config.

Unsure if this relates to this current issue, but this is something that's been requested multiple times in slack (bootc image channel) as well as meeting discussions.

I'll continue to use this issue to keep track of the progress, but if this is unrelated, please ping me and we can open up a separate issue regarding your description / ISO process!

**Comment by vrothberg** [comment]
> After discussions with [@deboer-tim](https://github.com/deboer-tim) in a previous call, we are going to go ahead with the implementation of a way to "automatically generate build config" with pre-defined details (ssh key, user, password, etc) for build config.

That sounds like a great feature to me.
